name: monitor-resources

services:
  # app:
  #   image: zed378/monitoring:latest
  #   container_name: app
  #   restart: always
  #   ports:
  #     - 6789:6789
  #   volumes:
  #     - ./log:/app/log
  #     - ./backup/:/app/backup
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     PORT: 6789
  #     SECRET: b5a4f2eea787e66215fa0887404b7aaa4a08b9a72b27e009734381cec4f6f28b8b00fb763e1ec90ae5a4d7da0c693572cb6016c33b6c8049b8e2202b4051c10a
  #     BACKUP_SCHEDULER: "0 0 * * *"

  #     # Database Conn
  #     DB_HOST: mysql
  #     DB_USER: root
  #     DB_PASS: ":ByOz70c>kel[f(r"
  #     DB_NAME: monitor
  #     DB_PORT: 3306
  #     DB_DIALECT: mysql

  #     # Cred
  #     PTOKEN: "ptr_WCZuwAEYqwkSHXtXtoUDVlQ/ld+Fng1CNGiJi+Bf9rk="
  #     PURL: https://10.1.200.5:9443/api

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ":ByOz70c>kel[f(r"
      MYSQL_DATABASE: monitor
      MYSQL_USER: monitor
      MYSQL_PASSWORD: ":ByOz70c>kel[f(r"
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql

  # Uncomment service below if you want to manage mysql
  # It automatically setup.
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ":ByOz70c>kel[f(r"
      MYSQL_PASSWORD: ":ByOz70c>kel[f(r"
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ":ByOz70c>kel[f(r"
    ports:
      - 8080:80
    depends_on:
      - mysql
